### ISSUE TITLE
\planetknown undefined

### ISSUE THREAD

**Issue by rodluger** [afeinstein20/v1298tau_tess#1]
https://github.com/afeinstein20/v1298tau_tess/runs/3955225597?check_suite_focus=true#step:3:1068

I'm working on making these builds easier to debug. Currently the helpful error messages always get buried!

Let me know if I can help with anything, btw. And please give me suggestions/feedback if you have any! Thx for using showyourwork!

**Comment by afeinstein20** [comment]
Ahh thank you!! Yeah, I've quickly learned most of the reasons the action fails is either (a) forgetting to import something or (b) forgetting the new command in the style.tex, like this issue! It's been pretty easy to use otherwise! 

Although getting figures to run has been challenging. From the docs, it seems like the label of the figure + the script + the pdf name all need to be the same and the action should pass? Or am I missing something?

**Comment by rodluger** [comment]
No problem! Thanks for bearing with me on this. It looks like you're using figure* environments, which I didn't add support for until yesterday. Can you do
```
pushd showyourwork
git fetch
git checkout v0.1.14
popd
```
and then commit & push your changes? That will update the workflow to the latest version, which should fix the error you're seeing.

**Comment by rodluger** [comment]
Awesome!
Yes, either manually, or have conda generate it: https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment
